# Generated by Django 3.2.3 on 2021-06-13 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalResume',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('languages_known', models.CharField(choices=[('HINDI', 'Hindi'), ('ENGLISH', 'English'), ('MARATHI', 'Marathi'), ('PUNJABI', 'Punjabi'), ('GUJRATI', 'Gujrati'), ('FRENCH', 'French')], max_length=15)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
