# Generated by Django 3.2.3 on 2021-06-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_resume', '0003_std_12'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_10',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Pursuing', 'Pursuing')], default='Passed', max_length=10),
        ),
        migrations.AddField(
            model_name='std_12',
            name='status',
            field=models.CharField(choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Pursuing', 'Pursuing')], default='Passed', max_length=10),
        ),
        migrations.AlterField(
            model_name='std_10',
            name='board',
            field=models.CharField(default='SSC', max_length=100),
        ),
        migrations.AlterField(
            model_name='std_12',
            name='board',
            field=models.CharField(default='HSC', max_length=100),
        ),
    ]
