# Generated by Django 3.2.3 on 2021-06-15 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('final_resume', '0004_auto_20210615_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='std_12',
            name='field',
            field=models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts')], default='Science', max_length=10),
        ),
        migrations.CreateModel(
            name='First_Year',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('year_of_passing', models.IntegerField(blank=True, choices=[(1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022)], null=True)),
                ('board', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.CharField(max_length=50)),
                ('percentage_or_cgpi', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('Passed', 'Passed'), ('Failed', 'Failed'), ('Pursuing', 'Pursuing')], default='Passed', max_length=10, null=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
