# Generated by Django 3.2.3 on 2021-06-15 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('final_resume', '0008_auto_20210615_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Detail',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Contact_no', models.IntegerField()),
                ('Nationality', models.CharField(max_length=100)),
                ('known_languages', models.CharField(max_length=150)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('room_no', models.CharField(max_length=150)),
                ('street_name', models.CharField(max_length=150)),
                ('locality', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('zipcode', models.IntegerField()),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='final_resume.personal_detail')),
            ],
        ),
    ]
