# Generated by Django 3.2.3 on 2021-06-08 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('writes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='poem_image',
        ),
    ]
