# Generated by Django 3.2.3 on 2021-06-08 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writes', '0002_remove_poem_poem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem_Images',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='poems/')),
                ('poem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='writes.poem')),
            ],
        ),
    ]
