# Generated by Django 3.2.3 on 2021-06-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writes', '0003_poem_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem_images',
            name='image',
        ),
        migrations.AddField(
            model_name='poem_images',
            name='poem_image',
            field=models.ImageField(blank=True, null=True, upload_to='poem_image/'),
        ),
    ]
