# Generated by Django 3.2.3 on 2021-06-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_code_link',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_website_link',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
