# Generated by Django 3.2.3 on 2021-06-18 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_image',
            name='username',
        ),
    ]
