from django.urls import path
from . import views
# from .views import ProfileDetail, TechnicalDetail
# from .views import Std_10_Update

urlpatterns = [
    path("post_resume/", views.post_resume, name="post_resume"),
    path("personal_detail_form/", views.personal_detail_form,
         name="personal_detail_form"),
    path("std_10_form/", views.std_10_form, name="std_10_form"),
    path("std_12_form/", views.std_12_form, name="std_12_form"),
    path("degree_details/", views.degree_details, name="degree_details"),
    path("first_year_form/", views.first_year_form, name="first_year_form"),
    path("second_year_form/", views.second_year_form, name="second_year_form"),
    path("third_year_form/", views.third_year_form, name="third_year_form"),
    path("fourth_year_form/", views.fourth_year_form, name="fourth_year_form"),
    path("technical_skills/", views.technical_skills, name="technical_skills"),
    path("Interests/", views.interests, name="Interests"),
    path("already_exist/", views.already_exist, name="already_exist"),
    path("pdf_detail/", views.view_detail_pdf, name="pdf_detail"),
    path("pdf_detail_images/", views.view_detail_pdf_images,
         name="pdf_detail_images"),
    path("final_pdf_images/", views.generate_pdf_images,
         name="final_pdf_images"),
    path("final_pdf/", views.generate_pdf, name="final_pdf"),
    # path("pdf_detail/<int:pk>/", ProfileDetail.as_view(), name="pdf_detail"),
    # path("pdf_detail/<int:pk>/", TechnicalDetail.as_view(), name="tech_detail"),
    path("std_10_update/", views.std_10_update, name="std_10_update"),
    path("std_12_update/", views.std_12_update, name="std_12_update"),
    path("first_year_update/", views.first_year_update, name="first_year_update"),
    path("second_year_update/", views.second_year_update,
         name="second_year_update"),
    path("third_year_update/", views.third_year_update, name="third_year_update"),
    path("fourth_year_update/", views.fourth_year_update,
         name="fourth_year_update"),
    path("personal_detail_update/", views.personal_detail_update,
         name="personal_detail_update"),
    path("technical_skills_update/", views.technical_skills_update,
         name="technical_skills_update"),
    path("interests_update/", views.interests_update,
         name="interests_update"),
    path("std_10_delete/", views.std_10_delete, name="std_10_delete"),
    path("std_12_delete/", views.std_12_delete, name="std_12_delete"),
    path("first_year_delete/", views.first_year_delete, name="first_year_delete"),
    path("second_year_delete/", views.second_year_delete,
         name="second_year_delete"),
    path("third_year_delete/", views.third_year_delete, name="third_year_delete"),
    path("fourth_year_delete/", views.fourth_year_delete,
         name="fourth_year_delete"),
    path("personal_detail_delete/", views.personal_detail_delete,
         name="personal_detail_delete"),
    path("technical_skills_delete/", views.technical_skills_delete,
         name="technical_skills_delete"),
    path("interests_delete/", views.interests_delete,
         name="interests_delete"),
]
