# Generated by Django 3.2.3 on 2021-06-09 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed_Image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feed_image', models.ImageField(blank=True, null=True, upload_to='feed_image/')),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.feed')),
            ],
        ),
    ]
