# Generated by Django 3.2.3 on 2021-05-30 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='user',
            new_name='username',
        ),
    ]
