# Generated by Django 3.2.3 on 2021-05-30 09:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('student', '0004_poem'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='poem_content',
            field=models.CharField(default='None', max_length=10000),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poem_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
        migrations.AlterField(
            model_name='poem',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
