# Generated by Django 3.2.3 on 2021-05-30 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20210530_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='poem_content',
            field=models.TextField(),
        ),
    ]
