# Generated by Django 3.2.3 on 2021-05-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='course_description',
            new_name='project_description',
        ),
    ]
