# Generated by Django 3.2.3 on 2021-05-30 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_rename_course_description_project_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='upload_images',
            field=models.FileField(default='default.jpg', upload_to='projects'),
        ),
    ]
