# Generated by Django 3.2.3 on 2021-06-18 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_certificate_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='course_platform',
            field=models.CharField(choices=[('COURSERA', 'Coursera'), ('UDEMY', 'Udemy'), ('EDX', 'Edx'), ('DRAWING', 'Drawing'), ('SPORTS', 'Sports'), ('OTHERS', 'Others')], max_length=8),
        ),
    ]
